parameters:
    craffft.single_session_storage.class: Craffft\SingleSessionStorageBundle\Storage\SingleSessionStorage

services:
    craffft.single_session_storage:
        class: %craffft.single_session_storage.class%
        arguments: ["@service_container"]
