services:
    Craffft\SingleSessionStorageBundle\Storage\SingleSessionStorage:
        arguments: ["@service_container"]
        public: true

    craffft.single_session_storage:
        alias: Craffft\SingleSessionStorageBundle\Storage\SingleSessionStorage
        public: true
